const cheerio = require("cheerio");
const axios = require("axios");

const {
  writeToFile,
  writeToFileLinks,
  writeToFileArray,
} = require("./file_write");

// const url = "https://theresanaiforthat.com/ai/talktotables/";
let array = [];

const url = [
  "https://aivalley.ai/tripnotes/",
  "https://aivalley.ai/dream-3d/",
  "https://aivalley.ai/flair-ai/",
  "https://aivalley.ai/albus/",
  "https://aivalley.ai/gptagent/",
  "https://aivalley.ai/promptlayer/",
  "https://aivalley.ai/clay/",
  "https://aivalley.ai/voicepen/",
  "https://aivalley.ai/string/",
  "https://aivalley.ai/ubos-ai/",
  "https://aivalley.ai/brandsnap-ai/",
  "https://aivalley.ai/plus-ai/",
  "https://aivalley.ai/levity/",
  "https://aivalley.ai/audio-pen/",
  "https://aivalley.ai/googles-styledrop/",
  "https://aivalley.ai/type/",
  "https://aivalley.ai/spline/",
  "https://aivalley.ai/reclaim/",
  "https://aivalley.ai/summate/",
  "https://aivalley.ai/narrated-tours/",
  "https://aivalley.ai/cyte-ai/",
  "https://aivalley.ai/my-mind/",
  "https://aivalley.ai/8320-2/",
  "https://aivalley.ai/magify-design/",
  "https://aivalley.ai/arch-synth/",
  "https://aivalley.ai/supabase-vector/",
  "https://aivalley.ai/anything-ai/",
  "https://aivalley.ai/roll/",
  "https://aivalley.ai/mirrorthink/",
  "https://aivalley.ai/pi/",
  "https://aivalley.ai/odin-ai/",
  "https://aivalley.ai/ortus/",
  "https://aivalley.ai/brain-fm/",
  "https://aivalley.ai/paragraphica/",
  "https://aivalley.ai/2short-ai-2/",
  "https://aivalley.ai/reimagine/",
  "https://aivalley.ai/graphy-ai/",
  "https://aivalley.ai/chatmind/",
  "https://aivalley.ai/capechat/",
  "https://aivalley.ai/heygen/",
  "https://aivalley.ai/studio-design/",
  "https://aivalley.ai/parrot-ai/",
  "https://aivalley.ai/contlo/",
  "https://aivalley.ai/wavtool/",
  "https://aivalley.ai/invideo/",
  "https://aivalley.ai/lovo/",
  "https://aivalley.ai/boxy/",
  "https://aivalley.ai/opera-aria/",
  "https://aivalley.ai/kai-keyboardai/",
  "https://aivalley.ai/lavender/",
  "https://aivalley.ai/soundstorm/",
  "https://aivalley.ai/mindsera-2/",
  "https://aivalley.ai/chatbase/",
  "https://aivalley.ai/pimeyes-ai/",
  "https://aivalley.ai/speechify/",
  "https://aivalley.ai/boost/",
  "https://aivalley.ai/11258-2/",
  "https://aivalley.ai/photoshop-ai/",
  "https://aivalley.ai/warpsound/",
  "https://aivalley.ai/privategpt/",
  "https://aivalley.ai/prompt-perfect/",
  "https://aivalley.ai/adcrafter-ai/",
  "https://aivalley.ai/diagram/",
  "https://aivalley.ai/bardeen-ai/",
  "https://aivalley.ai/pragma/",
  "https://aivalley.ai/metavoice-ai/",
  "https://aivalley.ai/ai-lawyer-2/",
  "https://aivalley.ai/9654-2/",
  "https://aivalley.ai/gencraft/",
  "https://aivalley.ai/build-ai/",
  "https://aivalley.ai/glasp-2/",
  "https://aivalley.ai/stablestudio/",
  "https://aivalley.ai/dora/",
  "https://aivalley.ai/chatgpt-for-ios/",
  "https://aivalley.ai/mind-video/",
  "https://aivalley.ai/dropchat/",
  "https://aivalley.ai/mindbot/",
  "https://aivalley.ai/boxy-2/",
  "https://aivalley.ai/parthean-ai/",
  "https://aivalley.ai/canva-text-to-image/",
  "https://aivalley.ai/8984-2/",
  "https://aivalley.ai/steno/",
  "https://aivalley.ai/muzify-ai/",
  "https://aivalley.ai/microsoft-365-copilot/",
  "https://aivalley.ai/superflow/",
  "https://aivalley.ai/leiapix/",
  "https://aivalley.ai/kickresume-2/",
  "https://aivalley.ai/eightlify/",
  "https://aivalley.ai/formx-2/",
  "https://aivalley.ai/ai-resource-finder-tool/",
  "https://aivalley.ai/tome/",
  "https://aivalley.ai/codeium/",
  "https://aivalley.ai/runwayml/",
  "https://aivalley.ai/paperade/",
  "https://aivalley.ai/adobe-firefly/",
  "https://aivalley.ai/aideamap/",
  "https://aivalley.ai/uizard-autodesigner/",
  "https://aivalley.ai/talk-to-books/",
  "https://aivalley.ai/grammarly/",
  "https://aivalley.ai/musiclm/",
  "https://aivalley.ai/stockimg-ai/",
  "https://aivalley.ai/ingestai/",
  "https://aivalley.ai/magic-studio-2/",
  "https://aivalley.ai/midjourney-prompt-helper/",
  "https://aivalley.ai/hoppycopy/",
  "https://aivalley.ai/adcreative-ai-2/",
  "https://aivalley.ai/mubert/",
  "https://aivalley.ai/kraftful-2/",
  "https://aivalley.ai/paperbrain/",
  "https://aivalley.ai/caktus/",
  "https://aivalley.ai/magical/",
  "https://aivalley.ai/midjourney/",
  "https://aivalley.ai/nightcafe-studio/",
  "https://aivalley.ai/playground-ai/",
  "https://aivalley.ai/fy-studio/",
  "https://aivalley.ai/pixelicious-2/",
  "https://aivalley.ai/playarti/",
  "https://aivalley.ai/civitai-2/",
  "https://aivalley.ai/ebsynth-2/",
  "https://aivalley.ai/instantart-io/",
  "https://aivalley.ai/arthub-2/",
  "https://aivalley.ai/dreamlike-art/",
  "https://aivalley.ai/lexica-2/",
  "https://aivalley.ai/ai-art-apps-database-2/",
  "https://aivalley.ai/mage-2/",
  "https://aivalley.ai/artflow-ai-2/",
  "https://aivalley.ai/vana-portrait-2/",
  "https://aivalley.ai/dream-up-deviant-art-2/",
  "https://aivalley.ai/astria-2/",
  "https://aivalley.ai/notion-ai/",
  "https://aivalley.ai/monica/",
  "https://aivalley.ai/gpt3-playground/",
  "https://aivalley.ai/glasp/",
  "https://aivalley.ai/analogenie/",
  "https://aivalley.ai/moji-writing-assistant-2/",
  "https://aivalley.ai/detect-gpt/",
  "https://aivalley.ai/frase/",
  "https://aivalley.ai/penelope-ai/",
  "https://aivalley.ai/undetectablegpt/",
  "https://aivalley.ai/rewriteit-ai/",
  "https://aivalley.ai/toolbuilder/",
  "https://aivalley.ai/schoolhack/",
  "https://aivalley.ai/arvin/",
  "https://aivalley.ai/gptionary/",
  "https://aivalley.ai/neurospell/",
  "https://aivalley.ai/corrector-app/",
  "https://aivalley.ai/evolv/",
  "https://aivalley.ai/kickresume/",
  "https://aivalley.ai/typly/",
  "https://aivalley.ai/maester-app/",
  "https://aivalley.ai/paragraphai/",
  "https://aivalley.ai/wordtune/",
  "https://aivalley.ai/othersideai/",
  "https://aivalley.ai/seotools/",
  "https://aivalley.ai/proposal-genie/",
  "https://aivalley.ai/webcopilot/",
  "https://aivalley.ai/text-generator-plugin/",
  "https://aivalley.ai/compose/",
  "https://aivalley.ai/nichess/",
  "https://aivalley.ai/autowrite-app/",
  "https://aivalley.ai/lex/",
  "https://aivalley.ai/optimo-3/",
  "https://aivalley.ai/copyleaks/",
  "https://aivalley.ai/quasi-2/",
  "https://aivalley.ai/ultrabrainstomer-2/",
  "https://aivalley.ai/verb-ai/",
  "https://aivalley.ai/ai-majic/",
  "https://aivalley.ai/aiprolific/",
  "https://aivalley.ai/novelflow-ai-2/",
  "https://aivalley.ai/machinetranslation/",
  "https://aivalley.ai/harpa-ai-2/",
  "https://aivalley.ai/evolup/",
  "https://aivalley.ai/seo-ai/",
  "https://aivalley.ai/keywrds-ai/",
  "https://aivalley.ai/ai-writer/",
  "https://aivalley.ai/writey-ai/",
  "https://aivalley.ai/bramework/",
  "https://aivalley.ai/thundercontent/",
  "https://aivalley.ai/topicmojo/",
  "https://aivalley.ai/neuronwriter/",
  "https://aivalley.ai/writer/",
  "https://aivalley.ai/spinrewriter/",
  "https://aivalley.ai/kafkai/",
  "https://aivalley.ai/growthbar/",
  "https://aivalley.ai/ctrify/",
  "https://aivalley.ai/blognlp/",
  "https://aivalley.ai/wordhero/",
  "https://aivalley.ai/scalenut/",
  "https://aivalley.ai/ib-monograph-assistant/",
  "https://aivalley.ai/contentdetector-ai/",
  "https://aivalley.ai/interestedinai/",
  "https://aivalley.ai/conker-ai-2/",
  "https://aivalley.ai/gptautobot/",
  "https://aivalley.ai/essay-builder-ai/",
  "https://aivalley.ai/samwell-ai/",
  "https://aivalley.ai/textero-ai/",
  "https://aivalley.ai/seo-web-search/",
  "https://aivalley.ai/careered-ai/",
  "https://aivalley.ai/one-click-article-creator-2/",
  "https://aivalley.ai/calligrapher-ai/",
  "https://aivalley.ai/shakespeare-ai-toolbar/",
  "https://aivalley.ai/grammar-checker-2/",
  "https://aivalley.ai/regex-generator-2/",
  "https://aivalley.ai/aiwritingpal/",
  "https://aivalley.ai/write-my-essays-ai/",
  "https://aivalley.ai/hyrable/",
  "https://aivalley.ai/imagetocaption-ai/",
  "https://aivalley.ai/captionr/",
  "https://aivalley.ai/this-model-does-not-exist/",
  "https://aivalley.ai/auto-gpt/",
  "https://aivalley.ai/ai-experiments-2/",
  "https://aivalley.ai/papers-gpt-2/",
  "https://aivalley.ai/alethea/",
  "https://aivalley.ai/ask-my-book-2/",
  "https://aivalley.ai/nsfw-checker/",
  "https://aivalley.ai/gpt-me/",
  "https://aivalley.ai/loopgpt/",
  "https://aivalley.ai/have-i-been-encoded-2/",
  "https://aivalley.ai/farm3d/",
  "https://aivalley.ai/humanfest/",
  "https://aivalley.ai/starbyface/",
  "https://aivalley.ai/chatfans/",
  "https://aivalley.ai/infinite-drum/",
  "https://aivalley.ai/powermode-ai-2/",
  "https://aivalley.ai/storyd/",
  "https://aivalley.ai/gptforslides/",
  "https://aivalley.ai/slidesai/",
  "https://aivalley.ai/magicslides/",
  "https://aivalley.ai/motionit-ai/",
  "https://aivalley.ai/beautiful-ai/",
  "https://aivalley.ai/airgram/",
  "https://aivalley.ai/myreport/",
  "https://aivalley.ai/powerpresent-ai/",
  "https://aivalley.ai/prezo/",
  "https://aivalley.ai/autoslide/",
  "https://aivalley.ai/oss-insight/",
  "https://aivalley.ai/neevaai/",
  "https://aivalley.ai/andi/",
  "https://aivalley.ai/civitai/",
  "https://aivalley.ai/context/",
  "https://aivalley.ai/generated-photos/",
  "https://aivalley.ai/fireflies-ai/",
  "https://aivalley.ai/chatgpt-chrome-extension/",
  "https://aivalley.ai/kailua-labs/",
  "https://aivalley.ai/one-more-ai/",
  "https://aivalley.ai/chainintelgpt/",
  "https://aivalley.ai/claros/",
  "https://aivalley.ai/producthunt-ai/",
  "https://aivalley.ai/have-i-been-encoded/",
  "https://aivalley.ai/searcholic/",
  "https://aivalley.ai/iask-ai/",
  "https://aivalley.ai/enhanced-chatgpt/",
  "https://aivalley.ai/noowai/",
  "https://aivalley.ai/metaphor-systems/",
  "https://aivalley.ai/chatgpt-for-search-engines/",
  "https://aivalley.ai/ask-an-ai/",
  "https://aivalley.ai/fathom-fm-2/",
  "https://aivalley.ai/crowdview/",
  "https://aivalley.ai/lexii-ai/",
  "https://aivalley.ai/bookabout/",
  "https://aivalley.ai/komo-search/",
  "https://aivalley.ai/superus/",
  "https://aivalley.ai/imaiger/",
  "https://aivalley.ai/shaped/",
  "https://aivalley.ai/everypixel/",
  "https://aivalley.ai/decktopus-ai/",
  "https://aivalley.ai/nuclia/",
  "https://aivalley.ai/gamma/",
  "https://aivalley.ai/arthub/",
  "https://aivalley.ai/nyx/",
  "https://aivalley.ai/askbrian-ai/",
  "https://aivalley.ai/chatba/",
  "https://aivalley.ai/virtual-sapiens-ai/",
  "https://aivalley.ai/slidebean/",
  "https://aivalley.ai/pitch/",
  "https://aivalley.ai/narraive/",
  "https://aivalley.ai/rosebud/",
  "https://aivalley.ai/capturelab-2/",
  "https://aivalley.ai/zevi-ai/",
  "https://aivalley.ai/you/",
  "https://aivalley.ai/lexica/",
  "https://aivalley.ai/algolia/",
  "https://aivalley.ai/stock-ai/",
  "https://aivalley.ai/krea-2/",
  "https://aivalley.ai/enterpix/",
  "https://aivalley.ai/mage/",
  "https://aivalley.ai/casetext-2/",
  "https://aivalley.ai/glean/",
  "https://aivalley.ai/looria-2/",
  "https://aivalley.ai/explore-ai/",
  "https://aivalley.ai/dream-up-deviant-art/",
  "https://aivalley.ai/cookup-ai/",
  "https://aivalley.ai/fast-ai/",
  "https://aivalley.ai/ai-experiments/",
  "https://aivalley.ai/ai-swot-analysis/",
  "https://aivalley.ai/promind/",
  "https://aivalley.ai/project-supplies-2/",
  "https://aivalley.ai/wisdomai/",
  "https://aivalley.ai/medium-jailbreak/",
  "https://aivalley.ai/chatgpt-2d/",
  "https://aivalley.ai/codenull-ai/",
  "https://aivalley.ai/rath-by-kanarie/",
  "https://aivalley.ai/onlycoms-com/",
  "https://aivalley.ai/nextthreebooks-2/",
  "https://aivalley.ai/ai-roguelite-2/",
  "https://aivalley.ai/pickaxe/",
  "https://aivalley.ai/the-simulation-2/",
  "https://aivalley.ai/opus-2/",
  "https://aivalley.ai/leonardo-ai/",
  "https://aivalley.ai/lablab-ai/",
  "https://aivalley.ai/phraser/",
  "https://aivalley.ai/unakin-3/",
  "https://aivalley.ai/flowgpt/",
  "https://aivalley.ai/booom-ai-2/",
  "https://aivalley.ai/ai-art-apps-database/",
  "https://aivalley.ai/the-ai-times/",
  "https://aivalley.ai/scenario-2/",
  "https://aivalley.ai/aidungeon-2/",
  "https://aivalley.ai/the-simulation/",
  "https://aivalley.ai/ready-player-me-3/",
  "https://aivalley.ai/playstrict/",
  "https://aivalley.ai/endlessvn-2/",
  "https://aivalley.ai/inworld-2/",
  "https://aivalley.ai/hexagram/",
  "https://aivalley.ai/ggpredict/",
  "https://aivalley.ai/hidden-door/",
  "https://aivalley.ai/ai-careers/",
  "https://aivalley.ai/aidungeon/",
  "https://aivalley.ai/chai/",
  "https://aivalley.ai/luma-ai/",
  "https://aivalley.ai/scenario/",
  "https://aivalley.ai/ludo/",
  "https://aivalley.ai/arcaneland/",
  "https://aivalley.ai/human-or-not/",
  "https://aivalley.ai/segmentle/",
  "https://aivalley.ai/siege-gpt/",
  "https://aivalley.ai/voicemaker/",
  "https://aivalley.ai/bestflights-2/",
  "https://aivalley.ai/ttslabs/",
  "https://aivalley.ai/convai/",
  "https://aivalley.ai/aiva/",
  "https://aivalley.ai/ask-my-book/",
  "https://aivalley.ai/audioread/",
  "https://aivalley.ai/listnr/",
  "https://aivalley.ai/fakeyou/",
  "https://aivalley.ai/looka/",
  "https://aivalley.ai/namecheap-logo-maker/",
  "https://aivalley.ai/brandmark-2/",
  "https://aivalley.ai/make-logo-ai-2/",
  "https://aivalley.ai/markopolo-2/",
  "https://aivalley.ai/marble/",
  "https://aivalley.ai/kreateable-2/",
  "https://aivalley.ai/scispace/",
  "https://aivalley.ai/frequently-ai/",
  "https://aivalley.ai/scholarcy/",
  "https://aivalley.ai/review-hero-ai/",
  "https://aivalley.ai/socratic-by-google/",
  "https://aivalley.ai/ai-logobrainstorm/",
  "https://aivalley.ai/riffusion/",
  "https://aivalley.ai/podcast-2/",
  "https://aivalley.ai/pdf-gpt-2/",
  "https://aivalley.ai/moji-writing-assistant/",
  "https://aivalley.ai/ai-toolbox-for-innovators/",
  "https://aivalley.ai/boomy/",
  "https://aivalley.ai/yc-funding-assistant-2/",
  "https://aivalley.ai/sharly-ai/",
  "https://aivalley.ai/pollinations/",
  "https://aivalley.ai/scisummary/",
  "https://aivalley.ai/harmonai/",
  "https://aivalley.ai/wisio/",
  "https://aivalley.ai/endel/",
  "https://aivalley.ai/natural-language-playlist/",
  "https://aivalley.ai/songr/",
  "https://aivalley.ai/explainpaper/",
  "https://aivalley.ai/artificial-intelligence-songwriter/",
  "https://aivalley.ai/papers-gpt/",
  "https://aivalley.ai/paperlist/",
  "https://aivalley.ai/musenet/",
  "https://aivalley.ai/iris-ai/",
  "https://aivalley.ai/summate-it/",
  "https://aivalley.ai/playlistgenius-ai/",
  "https://aivalley.ai/consensus-2/",
  "https://aivalley.ai/elicit-2/",
  "https://aivalley.ai/playlistable/",
  "https://aivalley.ai/cradle-3/",
  "https://aivalley.ai/evoke-music/",
  "https://aivalley.ai/staccato/",
  "https://aivalley.ai/vocal-remover-2/",
  "https://aivalley.ai/lemonaid-music/",
  "https://aivalley.ai/cassetteai-2/",
  "https://aivalley.ai/piano-genie/",
  "https://aivalley.ai/soundraw-2/",
  "https://aivalley.ai/landr/",
  "https://aivalley.ai/emergent-drums-2/",
  "https://aivalley.ai/open-voice-os/",
  "https://aivalley.ai/soundful/",
  "https://aivalley.ai/amper-music/",
  "https://aivalley.ai/sonify-2/",
  "https://aivalley.ai/daft-art/",
  "https://aivalley.ai/quasi/",
  "https://aivalley.ai/songtell/",
  "https://aivalley.ai/predict-ai-2/",
  "https://aivalley.ai/autodraw/",
  "https://aivalley.ai/octoicons-2/",
  "https://aivalley.ai/cool-gift-ideas/",
  "https://aivalley.ai/suggest-gift/",
  "https://aivalley.ai/elf-help/",
  "https://aivalley.ai/roomify-ai/",
  "https://aivalley.ai/giftastic-ai/",
  "https://aivalley.ai/gifts-genie/",
  "https://aivalley.ai/turncage-2/",
  "https://aivalley.ai/intelli-gift/",
  "https://aivalley.ai/roamaround/",
  "https://aivalley.ai/journeai/",
  "https://aivalley.ai/ai-trip-planner/",
  "https://aivalley.ai/smart-gift-ai/",
  "https://aivalley.ai/bestflights/",
  "https://aivalley.ai/gifthuntr/",
  "https://aivalley.ai/wayfind/",
  "https://aivalley.ai/plantripai/",
  "https://aivalley.ai/giftbox/",
  "https://aivalley.ai/traivl/",
  "https://aivalley.ai/triptip/",
  "https://aivalley.ai/genie-figma/",
  "https://aivalley.ai/tripplanner-ai/",
  "https://aivalley.ai/finch-3d/",
  "https://aivalley.ai/collovgpt/",
  "https://aivalley.ai/thediytrip/",
  "https://aivalley.ai/journeyplan/",
  "https://aivalley.ai/magician-figma/",
  "https://aivalley.ai/vacation-travel-chat-gpt/",
  "https://aivalley.ai/ai-backdrop/",
  "https://aivalley.ai/magic-studio/",
  "https://aivalley.ai/imagecolorizer/",
  "https://aivalley.ai/brand-ai-model-3/",
  "https://aivalley.ai/photo-ai/",
  "https://aivalley.ai/pebblely/",
  "https://aivalley.ai/cleanup-pictures/",
  "https://aivalley.ai/getimg-ai/",
  "https://aivalley.ai/erase-bg/",
  "https://aivalley.ai/astria/",
  "https://aivalley.ai/green-screen-ai/",
  "https://aivalley.ai/patterned-ai/",
  "https://aivalley.ai/rocketai-2/",
  "https://aivalley.ai/photoroom-2/",
  "https://aivalley.ai/clipdrop/",
  "https://aivalley.ai/pinegraph/",
  "https://aivalley.ai/designs-ai-2/",
  "https://aivalley.ai/erase-it/",
  "https://aivalley.ai/upscayl/",
  "https://aivalley.ai/magic-copy-2/",
  "https://aivalley.ai/pics-enhancer/",
  "https://aivalley.ai/pfpmaker/",
  "https://aivalley.ai/markmyimages/",
  "https://aivalley.ai/paint-ai/",
  "https://aivalley.ai/photoaid/",
  "https://aivalley.ai/polarr-copilots-2/",
  "https://aivalley.ai/face26/",
  "https://aivalley.ai/invokeai/",
  "https://aivalley.ai/upscale-media/",
  "https://aivalley.ai/dreamlife-ai/",
  "https://aivalley.ai/blend/",
  "https://aivalley.ai/imagen-ai/",
  "https://aivalley.ai/facetune/",
  "https://aivalley.ai/bgsub/",
  "https://aivalley.ai/mokker/",
  "https://aivalley.ai/img-upscaler/",
  "https://aivalley.ai/cleanup/",
  "https://aivalley.ai/watermarkremover-io/",
  "https://aivalley.ai/remini/",
  "https://aivalley.ai/outfits-ai/",
  "https://aivalley.ai/pixelhunter-2/",
  "https://aivalley.ai/what-font-is/",
  "https://aivalley.ai/myth-ai/",
  "https://aivalley.ai/paint-by-text/",
  "https://aivalley.ai/midjourney-splitter/",
  "https://aivalley.ai/befunky/",
  "https://aivalley.ai/restorephotos/",
  "https://aivalley.ai/bria/",
  "https://aivalley.ai/genusoft-ai/",
  "https://aivalley.ai/nostalgia-photo/",
  "https://aivalley.ai/ai-image-enlarger/",
  "https://aivalley.ai/goodhues-ai/",
  "https://aivalley.ai/lets-enhance/",
  "https://aivalley.ai/octoicons/",
  "https://aivalley.ai/quicktools-by-picsart/",
  "https://aivalley.ai/rerender-ai/",
  "https://aivalley.ai/ai-picasso/",
  "https://aivalley.ai/evoto-ai/",
  "https://aivalley.ai/quizgecko/",
  "https://aivalley.ai/visio-studio/",
  "https://aivalley.ai/topaz-photo-ai/",
  "https://aivalley.ai/hama-image-editing/",
  "https://aivalley.ai/bg-eraser/",
  "https://aivalley.ai/adcreative-ai/",
  "https://aivalley.ai/thumbnailai/",
  "https://aivalley.ai/predict-ai/",
  "https://aivalley.ai/luna-ai/",
  "https://aivalley.ai/perfectly-clear-video-2/",
  "https://aivalley.ai/rocketai/",
  "https://aivalley.ai/radiant-photo/",
  "https://aivalley.ai/remove-bg/",
  "https://aivalley.ai/photoroom/",
  "https://aivalley.ai/prodigy-ai/",
  "https://aivalley.ai/unlimitedgpt/",
  "https://aivalley.ai/gems/",
  "https://aivalley.ai/ask-marcus-aurelius/",
  "https://aivalley.ai/astrogpt/",
  "https://aivalley.ai/easymessage/",
  "https://aivalley.ai/atlancer-ai/",
  "https://aivalley.ai/faqx/",
  "https://aivalley.ai/cassetteai/",
  "https://aivalley.ai/emergent-drums/",
  "https://aivalley.ai/soundraw/",
  "https://aivalley.ai/sonify/",
  "https://aivalley.ai/what-on-earth/",
  "https://aivalley.ai/artflow-ai/",
  "https://aivalley.ai/roomgpt/",
  "https://aivalley.ai/graham-ai/",
  "https://aivalley.ai/ai-social-bio/",
  "https://aivalley.ai/photor-ai/",
  "https://aivalley.ai/skim-it/",
  "https://aivalley.ai/clips-ai-2/",
  "https://aivalley.ai/shuffll/",
  "https://aivalley.ai/munch/",
  "https://aivalley.ai/papercup/",
  "https://aivalley.ai/capturelab/",
  "https://aivalley.ai/storywizard/",
  "https://aivalley.ai/affable-ai/",
  "https://aivalley.ai/storiesforkids/",
  "https://aivalley.ai/2short-ai/",
  "https://aivalley.ai/jibewith/",
  "https://aivalley.ai/nolanai/",
  "https://aivalley.ai/pixelhunter/",
  "https://aivalley.ai/once-upon-a-bot/",
  "https://aivalley.ai/repl-ai/",
  "https://aivalley.ai/storypear/",
  "https://aivalley.ai/author-of-poems/",
  "https://aivalley.ai/ai-screenwriter/",
  "https://aivalley.ai/tuliaa-2/",
  "https://aivalley.ai/talkpal-2/",
  "https://aivalley.ai/deepswap/",
  "https://aivalley.ai/veed-io/",
  "https://aivalley.ai/polarr-copilots/",
  "https://aivalley.ai/centropo-2/",
  "https://aivalley.ai/prospre/",
  "https://aivalley.ai/chatgpt-sidebar/",
  "https://aivalley.ai/nutraiplan/",
  "https://aivalley.ai/nextthreebooks/",
  "https://aivalley.ai/cutout-pro/",
  "https://aivalley.ai/wonder-studio/",
  "https://aivalley.ai/sheldon-ai/",
  "https://aivalley.ai/travelmate/",
  "https://aivalley.ai/oxolo-com/",
  "https://aivalley.ai/qlip-ai/",
  "https://aivalley.ai/mymind/",
  "https://aivalley.ai/consumerai/",
  "https://aivalley.ai/lovegpt/",
  "https://aivalley.ai/mechanic-for-a-chat-2/",
  "https://aivalley.ai/novelflow-ai/",
  "https://aivalley.ai/fathom-fm/",
  "https://aivalley.ai/chatgenius/",
  "https://aivalley.ai/recipes-by-ai/",
  "https://aivalley.ai/ai-story-generator/",
  "https://aivalley.ai/finding-words/",
  "https://aivalley.ai/friends-fables/",
  "https://aivalley.ai/glow-ai-2/",
  "https://aivalley.ai/your-own-story-book/",
  "https://aivalley.ai/experai/",
  "https://aivalley.ai/network-ai/",
  "https://aivalley.ai/howtoreplyto/",
  "https://aivalley.ai/oscar/",
  "https://aivalley.ai/langotalk/",
  "https://aivalley.ai/getaiway/",
  "https://aivalley.ai/coach-marlee/",
  "https://aivalley.ai/tiny-storie-2/",
  "https://aivalley.ai/textgpt/",
  "https://aivalley.ai/playlistai/",
  "https://aivalley.ai/imaginaition-2/",
  "https://aivalley.ai/looria/",
  "https://aivalley.ai/pirr/",
  "https://aivalley.ai/storyscape-ai/",
  "https://aivalley.ai/movmi/",
  "https://aivalley.ai/zeemo/",
  "https://aivalley.ai/latte/",
  "https://aivalley.ai/translate-video/",
  "https://aivalley.ai/fineshare/",
  "https://aivalley.ai/resume-worded-2/",
  "https://aivalley.ai/captions/",
  "https://aivalley.ai/flawless-ai/",
  "https://aivalley.ai/vizard/",
  "https://aivalley.ai/quickvid-ai-2/",
  "https://aivalley.ai/pix2pix/",
  "https://aivalley.ai/wisecut/",
  "https://aivalley.ai/clippah/",
  "https://aivalley.ai/clips-ai/",
  "https://aivalley.ai/gling/",
  "https://aivalley.ai/dubverse/",
  "https://aivalley.ai/colourlab/",
  "https://aivalley.ai/unscreen-com/",
  "https://aivalley.ai/pictory/",
  "https://aivalley.ai/topaz-video-ai/",
  "https://aivalley.ai/contentfries/",
  "https://aivalley.ai/type-studio/",
  "https://aivalley.ai/sheetai-app/",
  "https://aivalley.ai/arcwise-ai/",
  "https://aivalley.ai/luminal/",
  "https://aivalley.ai/excel-formula-bot/",
  "https://aivalley.ai/sheetgod/",
  "https://aivalley.ai/highcharts/",
  "https://aivalley.ai/parsio/",
  "https://aivalley.ai/seamlessgpt/",
  "https://aivalley.ai/numerous-ai/",
  "https://aivalley.ai/autoquery-gpt/",
  "https://aivalley.ai/bosco/",
  "https://aivalley.ai/anania/",
  "https://aivalley.ai/gpt-workspace-2/",
  "https://aivalley.ai/entar-io/",
  "https://aivalley.ai/outline-ninja/",
  "https://aivalley.ai/ogen-ai/",
  "https://aivalley.ai/nextatlas/",
  "https://aivalley.ai/recital/",
  "https://aivalley.ai/promptloop/",
  "https://aivalley.ai/comment-analyzer/",
  "https://aivalley.ai/flowshot/",
  "https://aivalley.ai/formula-generator/",
  "https://aivalley.ai/charm/",
  "https://aivalley.ai/gpt-for-sheets/",
  "https://aivalley.ai/sheet/",
  "https://aivalley.ai/goodlookup/",
  "https://aivalley.ai/kreateable/",
  "https://aivalley.ai/post-ai/",
  "https://aivalley.ai/domainsgpt-2/",
  "https://aivalley.ai/quickvid-ai/",
  "https://aivalley.ai/logocreatorai/",
  "https://aivalley.ai/postly/",
  "https://aivalley.ai/postgenius-2/",
  "https://aivalley.ai/lilybank-ai/",
  "https://aivalley.ai/make-logo-ai/",
  "https://aivalley.ai/brandmark/",
  "https://aivalley.ai/neural-canvas/",
  "https://aivalley.ai/gitfluence/",
  "https://aivalley.ai/phind/",
  "https://aivalley.ai/amazon-codewhisperer-2/",
  "https://aivalley.ai/novelai/",
  "https://aivalley.ai/tabnine/",
  "https://aivalley.ai/copilot/",
  "https://aivalley.ai/endlessvn/",
  "https://aivalley.ai/programminghelper-2/",
  "https://aivalley.ai/subtxt/",
  "https://aivalley.ai/buildt/",
  "https://aivalley.ai/bito-2/",
  "https://aivalley.ai/ai-reality/",
  "https://aivalley.ai/ai-room-planner/",
  "https://aivalley.ai/autoregex/",
  "https://aivalley.ai/regex-generator/",
  "https://aivalley.ai/codacy/",
  "https://aivalley.ai/codeconvert-ai/",
  "https://aivalley.ai/dreamstaging-ai/",
  "https://aivalley.ai/ai-code-mentor/",
  "https://aivalley.ai/unakin-2/",
  "https://aivalley.ai/spacely-ai/",
  "https://aivalley.ai/pionexgpt-2/",
  "https://aivalley.ai/agilegpt-2/",
  "https://aivalley.ai/virtualstagingai/",
  "https://aivalley.ai/sourceai-2/",
  "https://aivalley.ai/google-colab-copilot-2/",
  "https://aivalley.ai/realty-ninja/",
  "https://aivalley.ai/codiumai/",
  "https://aivalley.ai/coolaiid/",
  "https://aivalley.ai/hacker-ai/",
  "https://aivalley.ai/duino-code-generator/",
  "https://aivalley.ai/mobel/",
  "https://aivalley.ai/sketch/",
  "https://aivalley.ai/airtest/",
  "https://aivalley.ai/blackbox-ai-2/",
  "https://aivalley.ai/maket/",
  "https://aivalley.ai/codeassist/",
  "https://aivalley.ai/hey-github-2/",
  "https://aivalley.ai/whatthediff/",
  "https://aivalley.ai/codesquire-2/",
  "https://aivalley.ai/drumloop-ai-2/",
  "https://aivalley.ai/humata-ai/",
  "https://aivalley.ai/donotpay/",
  "https://aivalley.ai/ask-ai-lawyer/",
  "https://aivalley.ai/peachly-ai-2/",
  "https://aivalley.ai/traverse-ai/",
  "https://aivalley.ai/ai-lawyer/",
  "https://aivalley.ai/maigon-io/",
  "https://aivalley.ai/samurai/",
  "https://aivalley.ai/gpt-twit-bot/",
  "https://aivalley.ai/optimo-2/",
  "https://aivalley.ai/stride/",
  "https://aivalley.ai/tweetstorm-ai/",
  "https://aivalley.ai/legalese-decoder/",
  "https://aivalley.ai/patentpal/",
  "https://aivalley.ai/ferret/",
  "https://aivalley.ai/detangle-ai/",
  "https://aivalley.ai/legal-robot/",
  "https://aivalley.ai/activazon/",
  "https://aivalley.ai/casetext/",
  "https://aivalley.ai/spellbook/",
  "https://aivalley.ai/facial-assessment-tool/",
  "https://aivalley.ai/woebot-health-2/",
  "https://aivalley.ai/whisper-ai/",
  "https://aivalley.ai/leny/",
  "https://aivalley.ai/hoku/",
  "https://aivalley.ai/ogimi-ai/",
  "https://aivalley.ai/ai-health-mind/",
  "https://aivalley.ai/tranquilfibroids/",
  "https://aivalley.ai/analyzgpt/",
  "https://aivalley.ai/mindmate/",
  "https://aivalley.ai/namelix/",
  "https://aivalley.ai/namy-ai/",
  "https://aivalley.ai/yourdoctor-ai/",
  "https://aivalley.ai/ideasai/",
  "https://aivalley.ai/rhetorai/",
  "https://aivalley.ai/powermode-ai/",
  "https://aivalley.ai/releasenote-ai/",
  "https://aivalley.ai/sommerai/",
  "https://aivalley.ai/ask-yc/",
  "https://aivalley.ai/tuliaa/",
  "https://aivalley.ai/logmeal/",
  "https://aivalley.ai/upheal/",
  "https://aivalley.ai/lavo-ai/",
  "https://aivalley.ai/happy-mama/",
  "https://aivalley.ai/glass-health/",
  "https://aivalley.ai/glow-ai/",
  "https://aivalley.ai/hippocratic-ai/",
  "https://aivalley.ai/awemyface-2/",
  "https://aivalley.ai/lunit-2/",
  "https://aivalley.ai/social-var/",
  "https://aivalley.ai/syllaby/",
  "https://aivalley.ai/finalscout/",
  "https://aivalley.ai/marketmuse/",
  "https://aivalley.ai/analisa-io/",
  "https://aivalley.ai/systeme/",
  "https://aivalley.ai/scrip-ai/",
  "https://aivalley.ai/imagine-me/",
  "https://aivalley.ai/animeai/",
  "https://aivalley.ai/avatarify/",
  "https://aivalley.ai/creasquare/",
  "https://aivalley.ai/livereacting-ai-3/",
  "https://aivalley.ai/hushl/",
  "https://aivalley.ai/in3d/",
  "https://aivalley.ai/hairstyleai-2/",
  "https://aivalley.ai/commentreply-ai/",
  "https://aivalley.ai/brand-buzz/",
  "https://aivalley.ai/unrealme/",
  "https://aivalley.ai/photoai/",
  "https://aivalley.ai/character-ai/",
  "https://aivalley.ai/zoocial-2/",
  "https://aivalley.ai/neuralstudio/",
  "https://aivalley.ai/theoasis/",
  "https://aivalley.ai/aragon-ai/",
  "https://aivalley.ai/4722-2/",
  "https://aivalley.ai/gemsouls/",
  "https://aivalley.ai/ready-player-me/",
  "https://aivalley.ai/pictodream/",
  "https://aivalley.ai/beb-ai/",
  "https://aivalley.ai/tribescaler/",
  "https://aivalley.ai/ai-time-machine/",
  "https://aivalley.ai/influencer-marketing-ai/",
  "https://aivalley.ai/dreampic-ai/",
  "https://aivalley.ai/recontent-ai/",
  "https://aivalley.ai/followr/",
  "https://aivalley.ai/instantgen-ai/",
  "https://aivalley.ai/ai-voice-assistant/",
  "https://aivalley.ai/brandwise-ai/",
  "https://aivalley.ai/hpweb-ai/",
  "https://aivalley.ai/nando-ai/",
  "https://aivalley.ai/adobe-enhance-speech/",
  "https://aivalley.ai/aicoustics/",
  "https://aivalley.ai/koe-recast/",
  "https://aivalley.ai/speechgen/",
  "https://aivalley.ai/voice-ai/",
  "https://aivalley.ai/castmagic/",
  "https://aivalley.ai/dux-soup/",
  "https://aivalley.ai/albert/",
  "https://aivalley.ai/booltool/",
  "https://aivalley.ai/brand-ai-model-2/",
  "https://aivalley.ai/stratup-ai/",
  "https://aivalley.ai/venthive/",
  "https://aivalley.ai/yc-funding-assistant/",
  "https://aivalley.ai/armchair/",
  "https://aivalley.ai/domain-brainstormer/",
  "https://aivalley.ai/arsturn-ai/",
  "https://aivalley.ai/intellibase/",
  "https://aivalley.ai/vizologi/",
  "https://aivalley.ai/smartflowai/",
  "https://aivalley.ai/asksumo/",
  "https://aivalley.ai/domainsgpt/",
  "https://aivalley.ai/galeby/",
  "https://aivalley.ai/raizer-2/",
  "https://aivalley.ai/adsgency-ai/",
  "https://aivalley.ai/postgenius/",
  "https://aivalley.ai/kraftful/",
  "https://aivalley.ai/ask-experts-ai/",
  "https://aivalley.ai/2ai-2/",
  "https://aivalley.ai/caroot/",
  "https://aivalley.ai/voiceful-io/",
  "https://aivalley.ai/aibrane/",
  "https://aivalley.ai/namesnack/",
  "https://aivalley.ai/noise-eraser/",
  "https://aivalley.ai/ultrabrainstomer/",
  "https://aivalley.ai/toobsquid/",
  "https://aivalley.ai/maverick/",
  "https://aivalley.ai/idea-buddy/",
  "https://aivalley.ai/writesmart/",
  "https://aivalley.ai/lalal-ai/",
  "https://aivalley.ai/naming-magic/",
  "https://aivalley.ai/revive/",
  "https://aivalley.ai/beatoven-ai/",
  "https://aivalley.ai/socialbee/",
  "https://aivalley.ai/audio-strip/",
  "https://aivalley.ai/voicemod/",
  "https://aivalley.ai/cleanvoice-ai/",
  "https://aivalley.ai/podcastle/",
  "https://aivalley.ai/altered/",
  "https://aivalley.ai/promptable/",
  "https://aivalley.ai/pheeds-prompt-silo/",
  "https://aivalley.ai/centropo/",
  "https://aivalley.ai/promptstacks/",
  "https://aivalley.ai/promptbox/",
  "https://aivalley.ai/revalio/",
  "https://aivalley.ai/markopolo/",
  "https://aivalley.ai/eye-for-ai/",
  "https://aivalley.ai/epique/",
  "https://aivalley.ai/jrnylist/",
  "https://aivalley.ai/publer-ai-assist/",
  "https://aivalley.ai/openart/",
  "https://aivalley.ai/tldr-bot/",
  "https://aivalley.ai/prompthero/",
  "https://aivalley.ai/krea/",
  "https://aivalley.ai/aicomment/",
  "https://aivalley.ai/flight-path/",
  "https://aivalley.ai/broadn/",
  "https://aivalley.ai/5-out/",
  "https://aivalley.ai/seomatic-ai/",
  "https://aivalley.ai/adline/",
  "https://aivalley.ai/namewizard-ai/",
  "https://aivalley.ai/qakaa-2/",
  "https://aivalley.ai/feedbird/",
  "https://aivalley.ai/aigur-dev/",
  "https://aivalley.ai/brndaddo/",
  "https://aivalley.ai/chatgpt-prompt-plus/",
  "https://aivalley.ai/linkedin-elevator-pitch-ai/",
  "https://aivalley.ai/adln/",
  "https://aivalley.ai/name-generator/",
  "https://aivalley.ai/scope-money/",
  "https://aivalley.ai/prompt-attack/",
  "https://aivalley.ai/snack-prompt/",
  "https://aivalley.ai/ai-templates/",
  "https://aivalley.ai/prompt-genie/",
  "https://aivalley.ai/herogpt/",
  "https://aivalley.ai/ultimate-blogging-companion/",
  "https://aivalley.ai/trickle-ai-prompts-warehouse/",
  "https://aivalley.ai/promptchainer/",
  "https://aivalley.ai/aiprm/",
  "https://aivalley.ai/midjourney-prompt-generator/",
  "https://aivalley.ai/__trashed-10/",
  "https://aivalley.ai/imi-prompt/",
  "https://aivalley.ai/thunderclapai/",
  "https://aivalley.ai/keywordsearch/",
  "https://aivalley.ai/nuelink/",
  "https://aivalley.ai/easyprompt/",
  "https://aivalley.ai/wudpecker/",
  "https://aivalley.ai/recurpost/",
  "https://aivalley.ai/chathub/",
  "https://aivalley.ai/profilepro/",
  "https://aivalley.ai/formwise-ai/",
  "https://aivalley.ai/tweet-writer-ai/",
  "https://aivalley.ai/spellprints/",
  "https://aivalley.ai/marketing-co-pilot-ai/",
  "https://aivalley.ai/ranknow-ai/",
  "https://aivalley.ai/keywords-everwhere/",
  "https://aivalley.ai/prompt-space/",
  "https://aivalley.ai/ai-prompt-randomizer/",
  "https://aivalley.ai/mygpt/",
  "https://aivalley.ai/lunit/",
  "https://aivalley.ai/pitchgrade/",
  "https://aivalley.ai/ichatwithgpt/",
  "https://aivalley.ai/productivegpt/",
  "https://aivalley.ai/brandbird/",
  "https://aivalley.ai/visualhound/",
  "https://aivalley.ai/rewritewise/",
  "https://aivalley.ai/botika-2/",
  "https://aivalley.ai/ai-mafia/",
  "https://aivalley.ai/fashionadvisorai/",
  "https://aivalley.ai/mathly/",
  "https://aivalley.ai/promptomania/",
  "https://aivalley.ai/woebot-health/",
  "https://aivalley.ai/awemyface/",
  "https://aivalley.ai/cradle/",
  "https://aivalley.ai/adept/",
  "https://aivalley.ai/consensus/",
  "https://aivalley.ai/elicit/",
  "https://aivalley.ai/galactica/",
  "https://aivalley.ai/podcast/",
  "https://aivalley.ai/conker-ai/",
  "https://aivalley.ai/pdf-gpt/",
  "https://aivalley.ai/imaginaition/",
  "https://aivalley.ai/treemind/",
  "https://aivalley.ai/deap-learning-labs/",
  "https://aivalley.ai/brand-ai-model/",
  "https://aivalley.ai/tinyeinstein-2/",
  "https://aivalley.ai/zoocial/",
  "https://aivalley.ai/tiipe/",
  "https://aivalley.ai/furwee/",
  "https://aivalley.ai/persana-ai/",
  "https://aivalley.ai/turnitin/",
  "https://aivalley.ai/educatorlab/",
  "https://aivalley.ai/quick-reply/",
  "https://aivalley.ai/mechanic-for-a-chat/",
  "https://aivalley.ai/pixelicious/",
  "https://aivalley.ai/polyglot-media/",
  "https://aivalley.ai/background-lol/",
  "https://aivalley.ai/evita-ai/",
  "https://aivalley.ai/scribble-diffusion/",
  "https://aivalley.ai/study-ai/",
  "https://aivalley.ai/ai-is-a-joke/",
  "https://aivalley.ai/celebrity-voice-changer-ai/",
  "https://aivalley.ai/stable-attribution/",
  "https://aivalley.ai/ebsynth/",
  "https://aivalley.ai/lumen5/",
  "https://aivalley.ai/genmo-ai/",
  "https://aivalley.ai/artiphoria/",
  "https://aivalley.ai/the-drive-ai/",
  "https://aivalley.ai/reface-ai/",
  "https://aivalley.ai/quench-ai/",
  "https://aivalley.ai/lensa/",
  "https://aivalley.ai/hairstyleai/",
  "https://aivalley.ai/unreal-meal/",
  "https://aivalley.ai/trinka-ai/",
  "https://aivalley.ai/asknotion/",
  "https://aivalley.ai/quizbot-ai/",
  "https://aivalley.ai/trellis/",
  "https://aivalley.ai/3654-2/",
  "https://aivalley.ai/crossplag/",
  "https://aivalley.ai/writefull/",
  "https://aivalley.ai/teacherbot/",
  "https://aivalley.ai/magic-form/",
  "https://aivalley.ai/livereacting-ai/",
  "https://aivalley.ai/nolej/",
  "https://aivalley.ai/tiny-storie/",
  "https://aivalley.ai/vieutopia/",
  "https://aivalley.ai/smodin/",
  "https://aivalley.ai/nijijourney/",
  "https://aivalley.ai/aigify/",
  "https://aivalley.ai/aicheatcheck/",
  "https://aivalley.ai/speakable/",
  "https://aivalley.ai/stable-diffusion/",
  "https://aivalley.ai/brain-buddy/",
  "https://aivalley.ai/helicone/",
  "https://aivalley.ai/sketchar/",
  "https://aivalley.ai/rtutor/",
  "https://aivalley.ai/google-colab-copilot/",
  "https://aivalley.ai/the-godchat/",
  "https://aivalley.ai/safurai/",
  "https://aivalley.ai/pionexgpt/",
  "https://aivalley.ai/unakin/",
  "https://aivalley.ai/regex-ai/",
  "https://aivalley.ai/gpt-lab/",
  "https://aivalley.ai/chatgpt-js/",
  "https://aivalley.ai/promptsandbox/",
  "https://aivalley.ai/freshly-ai/",
  "https://aivalley.ai/alpharesearch/",
  "https://aivalley.ai/talkme-ai/",
  "https://aivalley.ai/es-ai/",
  "https://aivalley.ai/botika/",
  "https://aivalley.ai/fabfab-ai/",
  "https://aivalley.ai/trade-foresight/",
  "https://aivalley.ai/trendspider/",
  "https://aivalley.ai/quadency/",
  "https://aivalley.ai/gorillaterminal-ai/",
  "https://aivalley.ai/zerotax-al/",
  "https://aivalley.ai/raizer/",
  "https://aivalley.ai/chefgpt/",
  "https://aivalley.ai/hair-by-ai/",
  "https://aivalley.ai/agilegpt/",
  "https://aivalley.ai/magicchat-ai/",
  "https://aivalley.ai/programminghelper/",
  "https://aivalley.ai/hey-github/",
  "https://aivalley.ai/blackbox-ai/",
  "https://aivalley.ai/amazon-codewhisperer/",
  "https://aivalley.ai/codesquire/",
  "https://aivalley.ai/sourceai/",
  "https://aivalley.ai/ai-code-reviewer/",
  "https://aivalley.ai/bito/",
  "https://aivalley.ai/dust/",
  "https://aivalley.ai/magickpen/",
  "https://aivalley.ai/superflow-rewrite/",
  "https://aivalley.ai/webuters-ai/",
  "https://aivalley.ai/one-click-article-creator/",
  "https://aivalley.ai/roast-dating/",
  "https://aivalley.ai/stylemyride-ai/",
  "https://aivalley.ai/2ai/",
  "https://aivalley.ai/content-generator-2/",
  "https://aivalley.ai/lettria/",
  "https://aivalley.ai/chatronai/",
  "https://aivalley.ai/plan-my-tour-asap/",
  "https://aivalley.ai/netus-ai/",
  "https://aivalley.ai/orkoi/",
  "https://aivalley.ai/grammar-checker/",
  "https://aivalley.ai/freeplantour/",
  "https://aivalley.ai/cowriter/",
  "https://aivalley.ai/creaitor-ai/",
  "https://aivalley.ai/automata/",
  "https://aivalley.ai/pencil/",
  "https://aivalley.ai/tugan-ai/",
  "https://aivalley.ai/eloise/",
  "https://aivalley.ai/magic-copy/",
  "https://aivalley.ai/virtuo/",
  "https://aivalley.ai/remail/",
  "https://aivalley.ai/mailbutler/",
  "https://aivalley.ai/qakaa/",
  "https://aivalley.ai/fylan/",
  "https://aivalley.ai/madison-ai/",
  "https://aivalley.ai/klart-ai/",
  "https://aivalley.ai/gpt-workspace/",
  "https://aivalley.ai/listingcopy/",
  "https://aivalley.ai/superteam/",
  "https://aivalley.ai/reetail/",
  "https://aivalley.ai/mysticslabs-ai/",
  "https://aivalley.ai/turncage/",
  "https://aivalley.ai/peachly-ai/",
  "https://aivalley.ai/pixiebrix/",
  "https://aivalley.ai/simpler/",
  "https://aivalley.ai/copymatic/",
  "https://aivalley.ai/project-supplies/",
  "https://aivalley.ai/relayed/",
  "https://aivalley.ai/swapp/",
  "https://aivalley.ai/oracle/",
  "https://aivalley.ai/typingmind/",
  "https://aivalley.ai/yarnit/",
  "https://aivalley.ai/gerwin/",
  "https://aivalley.ai/circle-chat/",
  "https://aivalley.ai/jounce-ai/",
  "https://aivalley.ai/aizonix/",
  "https://aivalley.ai/whisper-memos/",
  "https://aivalley.ai/gpt-minus1/",
  "https://aivalley.ai/shakespeare/",
  "https://aivalley.ai/noty-ai/",
  "https://aivalley.ai/booom-ai/",
  "https://aivalley.ai/gpt-go/",
  "https://aivalley.ai/looria-ai/",
  "https://aivalley.ai/resume-worded/",
  "https://aivalley.ai/microsoft-bings-image-creator/",
  "https://aivalley.ai/dalle-2/",
  "https://aivalley.ai/craiyon/",
  "https://aivalley.ai/nextatlas-generate/",
  "https://aivalley.ai/formx/",
];

async function getLinks() {
  for (let i = 0; i < url.length; i++) {
    const result = await axios
      .get(url[i])
      .then((response) => {
        const data = cheerio.load(response.data);

        // console.log(data);
        let title,
          description,
          category,
          tags = [],
          image;

        // get title
        let getName = data("#main-container").find(".hero-section");
        getName = getName.find(".page-title");
        title = getName.text().trim();

        // get description
        let getDescription = data("#main").find(".entry-content");
        //   descriptionPrimary should be first p tag's text
        let descriptionPrimary = getDescription.find("p").first().text().trim();
        description = getDescription.find("ul");
        //   get text from multiple li in the ul
        description = description
          .find("li")
          .map((index, element) => {
            return data(element).text().trim();
          })
          .get()
          .join("\n");

        description =
          descriptionPrimary + "\n" + "Features: " + "\n" + description;

        // get tags
        data(".entry-tags").each((index, element) => {
          let tagText = data(element).text().trim();
          // delete first character if it is a #
          if (tagText[0] === "#") {
            tagText = tagText.slice(1);
          }
          tags.push(tagText);
        });

        // get category
        let getCategory = data(".1-item").find("a");
        category = getCategory.find("span").text().trim();

        // get image
        let getImage = data(".ct-featured-image").find(".ct-image-container");
        image = getImage.find("img").attr("src");

        array.push({
          title,
          description,
          category,
          tags,
          image,
        });

        console.log(i);
      })
      .catch((error) => {
        console.log(error);
      });
  }

  writeToFileArray(array, "aiValleyAllToolDetails.txt");
}

getLinks();

// arrayToScrape.forEach((url) => {
//   axios
//     .get(url)
//     .then((response) => {
//       const data = cheerio.load(response.data);

//       // console.log(data);
//       let title,
//         description,
//         category,
//         tags = [],
//         image;

//       // get title
//       let getName = data("#main-container").find(".hero-section");
//       getName = getName.find(".page-title");
//       title = getName.text().trim();

//       // get description
//       let getDescription = data("#main").find(".entry-content");
//       //   descriptionPrimary should be first p tag's text
//       let descriptionPrimary = getDescription.find("p").first().text().trim();
//       description = getDescription.find("ul");
//       //   get text from multiple li in the ul
//       description = description
//         .find("li")
//         .map((index, element) => {
//           return data(element).text().trim();
//         })
//         .get()
//         .join("\n");

//       description =
//         descriptionPrimary + "\n" + "Features: " + "\n" + description;

//       // get tags
//       data(".entry-tags").each((index, element) => {
//         let tagText = data(element).text().trim();
//         // delete first character if it is a #
//         if (tagText[0] === "#") {
//           tagText = tagText.slice(1);
//         }
//         tags.push(tagText);
//       });

//       // get category
//       let getCategory = data(".1-item").find("a");
//       category = getCategory.find("span").text().trim();

//       // get image
//       let getImage = data(".ct-featured-image").find(".ct-image-container");
//       image = getImage.find("img").attr("src");

//       array.push({
//         title,
//         description,
//         category,
//         tags,
//         image,
//       });

//     })
//     .catch((error) => {
//       console.log(error);
//     });
// });
